-- automatically generated by BNF Converter
module Main where


import System.IO ( stdin, hGetContents )
import System.Environment ( getArgs, getProgName )
import System.Exit ( exitFailure, exitSuccess )

import LexM
import ParM
import SkelM
import PrintM
import AbsM
import AstM as A
import ErrM

main = do
  interact interpM
  putStrLn ""

interpM s = 
  let OK tree = pProg (myLexer s)
  in show (transProg tree)
